# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKniYgdWYIpVRkH5iZsNMwSgBoBtq1oa
"""

import streamlit as st
import pickle
import numpy as np
import requests
import io

# GitHub raw file URL for your .pkl file
GITHUB_PKL_URL = "https://raw.githubusercontent.com/your-username/your-repo/main/linear_regression_model.pkl"

# Load model from GitHub
response = requests.get(GITHUB_PKL_URL)
model = pickle.load(io.BytesIO(response.content))

# Streamlit app
st.title("💼 Salary Prediction App")
st.write("Predict salary based on age using a pre-trained Linear Regression model.")

# Input from user
age = st.number_input("Enter Age:", min_value=18, max_value=70, value=25)

if st.button("Predict Salary"):
    prediction = model.predict(np.array([[age]]))[0]
    st.success(f"Predicted Salary: ₹{prediction:,.2f}")